---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: Shivanirudh
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: ensure required pip-packages are installed
      pip:
      name:
        - docker>=1.8.0
    - name: Pull Docker Image
      docker_image:
        name: "shivanirudh/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator shivanirudh/calculator
